### ISSUE TITLE
Clean up JS formatting

### ISSUE THREAD

**Issue by khawkins** [salesforce/offline-app-developer-starter-kit#3]
We already have `prettier` installed in the project, with npm scripts configured to execute it. We should clean up our code, then set prettier to manage our JS styles.

**Clean up**

- Add the following `.prettierignore` file at the top of the project:

```
/.sfdx/
/.sf/
```

- Clean up the npm scripts in `package.json` to just run against JS files at this point:

```json
"scripts": {
    // ...
    "prettier": "prettier --write \"**/*.js\"",
    // ...
}
```

- Run the following:

```bash
$ npm install
$ npm run prettier
$ # PR those changes
```

**Manage**
Add the following `.vscode/settings.json` entries (and the file itself, if it doesn't exist):

```json
{
    // enable globally (here: format on save)
    "editor.formatOnSave": true,

    // enable per-language (here: Prettier as formatter)
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    }
}
```

This will automatically fix `prettier` issues every time you save a file.

**Comment by dbreese** [comment]
Our package.json does have the following scripts already defined -- should we update these, too? 

```
    "prettier": "prettier --write \"**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml}\"",
    "prettier:verify": "prettier --list-different \"**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml}\""
```

Perhaps updating to use "force-app/**/*" instead of "**/*"?

**Comment by khawkins** [comment]
Ah I didn't see those! Also, from their docs:

> Prettier CLI will ignore files located in node_modules directory. To opt out from this behavior, use --with-node-modules flag.

Which was my main concern. So the top-level `**` seems good to me, in that case.

**Comment by dbreese** [comment]
I just ran `npm run prettier` and it attempts to format stuff under .sfdc, too.

Also, it really hosed a bunch of files by forcing quotes around things like `onclick={onClick}` (without quotes) which was changed to `onclick="{onClick}"` (with quotes), so we can leave this item open and figure it out later.

**Comment by khawkins** [comment]
> Also, it really hosed a bunch of files by forcing quotes around things like onclick={onClick}

Ugh. 🙂 I amended the task to include ignoring the CLI directories. Let's also update to just work on JS files. I think that's the bulk of what we care about anyway.
